http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  tasksApi:
    host: localhost
    paths: '/tasks'
serviceEndpoints:
  tasksService:
    url: 'http://localhost:8081/api'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: tasks
    apiEndpoints:
      - tasksApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: tasksService
              changeOrigin: true
